name: heropedia
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  http: ^0.13.4
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: Saira
      fonts:
        - asset: assets/fonts/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/SairaSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SairaSemiCondensed-Bold.ttf
          weight: 700